package accounts

import (
	"gamebackend/lifecycle"
	"gamebackend/modules/accounts/accountsapi"
	"gamebackend/modules/accounts/accountsauthrpc"
	"gamebackend/opsapi"
)

// registerPlayerOps contributes the accounts player operations. Route, HTTP↔wire
// binding and in-process invoker are all GENERATED by rpcgen from accountsapi.Auth
// + its HTTPBindings, so the gateway's LocalBackend and RemoteBackend consume the
// SAME wire envelopes. register/login are contributed only under devAuth, loginEpic
// only when the epic provider is up, me always — mirroring the old conditional
// route registration. svc (a *service) satisfies accountsapi.Auth.
func registerPlayerOps(ctx *lifecycle.Context, svc *service, devAuth, epicEnabled bool) {
	// Pass the service to the generated glue AS the pure capability interface.
	var impl accountsapi.Auth = svc
	ops := accountsauthrpc.Operations(impl)
	if devAuth {
		contributeOp(ctx, ops[accountsauthrpc.MethodRegister])
		contributeOp(ctx, ops[accountsauthrpc.MethodLogin])
	}
	if epicEnabled {
		contributeOp(ctx, ops[accountsauthrpc.MethodLoginEpic])
	}
	contributeOp(ctx, ops[accountsauthrpc.MethodMe])
}

// contributeOp contributes one generated operation to the three gateway slots.
func contributeOp(ctx *lifecycle.Context, op opsapi.OpSet) {
	ctx.Contribute(opsapi.Slot, op.Operation)
	ctx.Contribute(opsapi.BindingSlot, op.Binding)
	ctx.Contribute(opsapi.LocalSlot, op.Local)
}
