// Code generated by rpcgen; DO NOT EDIT.

package charactersrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/characters/charactersapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodOwnerOf = "characters.ownerOf"
)

// ownerOfRequest is the wire request envelope for OwnerOf.
type ownerOfRequest struct {
	CharacterID string `json:"characterID"`
}

// ownerOfResponse is the wire response envelope for OwnerOf. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type ownerOfResponse struct {
	Status   opsapi.Status `json:"status"`
	Err      string        `json:"err,omitempty"`
	PlayerID string        `json:"playerID"`
	Ok       bool          `json:"ok"`
}

// Client implements charactersapi.Ownership over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ charactersapi.Ownership = (*Client)(nil)

// OwnerOf implements the capability by calling characters.ownerOf over the transport.
func (c *Client) OwnerOf(ctx context.Context, a0 string) (r0 string, r1 bool, err error) {
	req := ownerOfRequest{CharacterID: a0}
	var resp ownerOfResponse
	if err = c.caller.Call(ctx, MethodOwnerOf, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.PlayerID
	r1 = resp.Ok
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one handler per method. *edge.Server satisfies it.
type Registrar interface {
	Handle(method string, h edge.Handler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with context.Background() (matching
// the hand-written adapters — NO ctx propagation), and marshals the response
// envelope, folding a returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl charactersapi.Ownership) {
	reg.Handle(MethodOwnerOf, func(reqPayload []byte) ([]byte, error) {
		var req ownerOfRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, r1, err := impl.OwnerOf(context.Background(), req.CharacterID)
		resp := ownerOfResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.PlayerID = r0
			resp.Ok = r1
		}
		return json.Marshal(resp)
	})
}
