package characters

import (
	"gamebackend/lifecycle"
	"gamebackend/modules/characters/charactersapi"
	"gamebackend/modules/characters/charactersplayerrpc"
	"gamebackend/opsapi"
)

// registerPlayerOps contributes the three player operations (create/list/delete).
// Route, HTTP↔wire binding (Decode/NewResp/Encode) and in-process invoker are all
// GENERATED by rpcgen from charactersapi.Player + its HTTPBindings, so the
// gateway's LocalBackend and RemoteBackend consume the SAME wire envelopes — one
// source of truth, remote dispatch correct for every op shape. svc (a *service)
// satisfies charactersapi.Player.
func registerPlayerOps(ctx *lifecycle.Context, svc *service) {
	// Hand the service to the generated glue AS the pure capability interface (not
	// the concrete *service), so the glue depends on the contract, never the impl.
	var impl charactersapi.Player = svc
	for _, op := range charactersplayerrpc.Operations(impl) {
		ctx.Contribute(opsapi.Slot, op.Operation)
		ctx.Contribute(opsapi.BindingSlot, op.Binding)
		ctx.Contribute(opsapi.LocalSlot, op.Local)
	}
}
