//! The emit phase (Step 3): turn the scraped [`Manifest`] into deterministic C# under
//! `clients/csharp/Generated/`. Three files, namespace `GameBackend.Client.Generated`:
//!
//! - `Status.cs` — the `Status` enum (variant names verbatim; round-trips via
//!   `JsonStringEnumConverter`).
//! - `Dtos.cs` — one positional `record` per DTO, `[property: JsonPropertyName]` on
//!   EVERY field (the wire keys are snake_case and `System.Text.Json` is case-sensitive).
//! - `Client.cs` — the two exception types, one request `record` per method (empty ⇒
//!   serializes to `{}`, never `null` — the Step-1 live-verified rule), and
//!   `GameBackendClient(IPlayerTransport)` with one `async` method per reachable op.
//!
//! Output is byte-stable: fixed header (no timestamp/version), methods in the manifest's
//! sorted order, fields in declaration order, LF newlines. Step 5's freshness gate
//! (`git diff --exit-code`) depends on this.
//!
//! Method-naming scheme: `<PascalProvider><CapFirst(methodSuffix)>Async`, e.g.
//! `characters.create` → `CharactersCreateAsync`, `inventory.listMine` →
//! `InventoryListMineAsync`, `leaderboard.topScores` → `LeaderboardTopScoresAsync`. The
//! provider prefix disambiguates same-named ops across providers (two `list`s).

use std::path::Path;

use anyhow::{Context as _, Result};

use crate::model::{DtoDef, Manifest, MethodDef, TypeRef};

const NS: &str = "GameBackend.Client.Generated";

/// Fixed provenance header prepended to every emitted file — NO timestamp/version so the
/// output is byte-stable for the freshness gate.
const HEADER: &str = "// <auto-generated>\n\
    //     Generated by tools/csharp-client-gen. DO NOT EDIT BY HAND.\n\
    //     Regenerate: cargo run -p csharp-client-gen -- --out clients/csharp/Generated\n\
    // </auto-generated>\n\
    \n\
    // The <auto-generated> marker above puts this file OUTSIDE the project nullable\n\
    // context, so the annotations below need an explicit directive (else CS8669).\n\
    #nullable enable\n";

/// Emits the three C# files into `out_dir`, creating it if needed.
pub fn emit(manifest: &Manifest, out_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("create output dir {}", out_dir.display()))?;
    for (name, body) in [
        ("Status.cs", emit_status(manifest)),
        ("Dtos.cs", emit_dtos(manifest)),
        ("Client.cs", emit_client(manifest)),
    ] {
        let path = out_dir.join(name);
        std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Status.cs
// ---------------------------------------------------------------------------

/// The `Status` enum, variants in declaration order. The wire form is the exact variant
/// name, so a `JsonStringEnumConverter` round-trips it with no `[EnumMember]` renames.
pub fn emit_status(m: &Manifest) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str(&format!("namespace {NS};\n\n"));
    s.push_str("/// <summary>\n");
    s.push_str("/// The domain outcome taxonomy (mirrors <c>opsapi::Status</c>). The wire form is the\n");
    s.push_str("/// exact variant name; a <c>JsonStringEnumConverter</c> round-trips it.\n");
    s.push_str("/// </summary>\n");
    s.push_str("public enum Status\n{\n");
    for v in &m.statuses {
        s.push_str(&format!("    {v},\n"));
    }
    s.push_str("}\n");
    s
}

// ---------------------------------------------------------------------------
// Dtos.cs
// ---------------------------------------------------------------------------

/// One positional `record` per DTO. Every field carries `[property: JsonPropertyName]`
/// (not only renamed ones) — the wire keys are snake_case and STJ is case-sensitive.
pub fn emit_dtos(m: &Manifest) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str("using System.Text.Json.Serialization;\n\n");
    s.push_str(&format!("namespace {NS};\n"));
    for dto in &m.dtos {
        s.push('\n');
        s.push_str(&emit_dto(dto));
    }
    s
}

fn emit_dto(dto: &DtoDef) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// <summary>The <c>{}</c> DTO.</summary>\n",
        dto.name
    ));
    let members: Vec<String> = dto
        .fields
        .iter()
        .map(|f| {
            format!(
                "    [property: JsonPropertyName(\"{}\")] {} {}",
                f.wire_name,
                cs_type(&f.ty),
                pascal_from_snake(&f.name)
            )
        })
        .collect();
    s.push_str(&format!("public sealed record {}(\n", dto.name));
    s.push_str(&members.join(",\n"));
    s.push_str(");\n");
    s
}

// ---------------------------------------------------------------------------
// Client.cs
// ---------------------------------------------------------------------------

/// The exceptions, the per-method request records, and `GameBackendClient`.
pub fn emit_client(m: &Manifest) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str("using System.Text.Json;\n");
    s.push_str("using System.Text.Json.Nodes;\n");
    s.push_str("using System.Text.Json.Serialization;\n");
    s.push_str("using GameBackend.Client.Transport;\n\n");
    s.push_str(&format!("namespace {NS};\n\n"));

    // --- Exceptions ---
    s.push_str(
        "/// <summary>A transport-level fault (framing / envelope / unwired front): the\n\
         /// player response arrived with <c>ok == false</c>, or the envelope was malformed.</summary>\n",
    );
    s.push_str(
        "public sealed class GameBackendTransportException(string? error)\n\
         \x20   : Exception(error ?? \"player transport fault\");\n\n",
    );
    s.push_str(
        "/// <summary>A completed operation whose domain <c>status</c> was not <c>Ok</c>.\n\
         /// <see cref=\"Status\"/> is the outcome; <see cref=\"Detail\"/> is the server's <c>err</c>.</summary>\n",
    );
    s.push_str(
        "public sealed class GameBackendStatusException(Status status, string? detail)\n\
         \x20   : Exception($\"operation failed with status {status}: {detail ?? \"<no detail>\"}\")\n\
         {\n\
         \x20   /// <summary>The non-<c>Ok</c> domain status.</summary>\n\
         \x20   public Status Status { get; } = status;\n\
         \x20   /// <summary>The server-supplied error detail, if any.</summary>\n\
         \x20   public string? Detail { get; } = detail;\n\
         }\n\n",
    );

    // --- Request records (one per method, in manifest order) ---
    for method in &m.methods {
        s.push_str(&emit_request_record(method));
        s.push('\n');
    }

    // --- The client ---
    s.push_str(
        "/// <summary>\n\
         /// The generated, typed player client. Each method builds a request DTO (always a\n\
         /// concrete object — a no-arg call serializes to <c>{}</c>, never <c>null</c>),\n\
         /// dispatches it over <see cref=\"IPlayerTransport\"/>, then unwraps the domain\n\
         /// envelope: a transport fault throws <see cref=\"GameBackendTransportException\"/>, a\n\
         /// non-<c>Ok</c> status throws <see cref=\"GameBackendStatusException\"/>.\n\
         /// </summary>\n",
    );
    s.push_str("public sealed class GameBackendClient(IPlayerTransport transport)\n{\n");
    s.push_str(
        "    private static readonly JsonSerializerOptions JsonOpts = new()\n\
         \x20   {\n\
         \x20       Converters = { new JsonStringEnumConverter() },\n\
         \x20   };\n\n",
    );

    for (i, method) in m.methods.iter().enumerate() {
        if i > 0 {
            s.push('\n');
        }
        s.push_str(&emit_method(method));
    }

    // --- Shared unwrap helper ---
    s.push('\n');
    s.push_str(
        "    /// <summary>Validates the transport flag and the domain status, returning the\n\
         \x20   /// payload envelope on success.</summary>\n\
         \x20   private static JsonNode Unwrap(PlayerResponse resp)\n\
         \x20   {\n\
         \x20       if (!resp.Ok)\n\
         \x20           throw new GameBackendTransportException(resp.Error);\n\
         \x20       JsonNode payload = resp.Payload\n\
         \x20           ?? throw new GameBackendTransportException(\"transport reported ok but no payload envelope\");\n\
         \x20       JsonNode statusNode = payload[\"status\"]\n\
         \x20           ?? throw new GameBackendTransportException(\"response envelope missing 'status'\");\n\
         \x20       Status status = statusNode.Deserialize<Status>(JsonOpts);\n\
         \x20       if (status != Status.Ok)\n\
         \x20           throw new GameBackendStatusException(status, payload[\"err\"]?.GetValue<string>());\n\
         \x20       return payload;\n\
         \x20   }\n",
    );
    s.push_str("}\n");
    s
}

/// The request `record` for one method — one positional param per arg (empty when none,
/// which serializes to `{}`). `[property: JsonPropertyName]` carries the wire key.
fn emit_request_record(method: &MethodDef) -> String {
    let name = format!("{}Request", op_base(method));
    if method.args.is_empty() {
        return format!(
            "/// <summary>Request for <c>{}</c> (no arguments — serializes to <c>{{}}</c>).</summary>\n\
             public sealed record {name}();\n",
            method.wire_method
        );
    }
    let members: Vec<String> = method
        .args
        .iter()
        .map(|a| {
            format!(
                "    [property: JsonPropertyName(\"{}\")] {} {}",
                a.wire_name,
                cs_type(&a.ty),
                pascal_from_snake(&a.name)
            )
        })
        .collect();
    format!(
        "/// <summary>Request for <c>{}</c>.</summary>\n\
         public sealed record {name}(\n{});\n",
        method.wire_method,
        members.join(",\n")
    )
}

/// One typed async client method.
fn emit_method(method: &MethodDef) -> String {
    let ret = return_type(&method.ret);
    let mut params: Vec<String> = Vec::new();
    let player = method.auth == "player";
    if player {
        params.push("string token".to_string());
    }
    for a in &method.args {
        params.push(format!("{} {}", cs_type(&a.ty), escape_ident(&camel_from_snake(&a.name))));
    }
    params.push("CancellationToken ct = default".to_string());

    let req_name = format!("{}Request", op_base(method));
    let ctor_args: Vec<String> = method
        .args
        .iter()
        .map(|a| escape_ident(&camel_from_snake(&a.name)))
        .collect();
    let token_expr = if player { "token" } else { "null" };

    let mut s = String::new();
    s.push_str(&format!(
        "    /// <summary>Invokes <c>{}</c> ({}).</summary>\n",
        method.wire_method,
        if player { "requires a bearer token" } else { "unauthenticated" }
    ));
    s.push_str(&format!(
        "    public async {ret} {}Async({})\n    {{\n",
        op_base(method),
        params.join(", ")
    ));
    s.push_str(&format!(
        "        var request = new {req_name}({});\n",
        ctor_args.join(", ")
    ));
    s.push_str("        byte[] payload = JsonSerializer.SerializeToUtf8Bytes(request, JsonOpts);\n");
    s.push_str(&format!(
        "        PlayerResponse resp = await transport.CallAsync(\"{}\", {token_expr}, payload, ct).ConfigureAwait(false);\n",
        method.wire_method
    ));
    match &method.ret {
        TypeRef::Unit => {
            s.push_str("        Unwrap(resp);\n");
        }
        _ => {
            let cs = cs_type(&method.ret);
            s.push_str("        JsonNode envelope = Unwrap(resp);\n");
            s.push_str(&format!(
                "        JsonNode value = envelope[\"value\"]\n\
                 \x20           ?? throw new GameBackendTransportException(\"Ok response missing 'value'\");\n\
                 \x20       return value.Deserialize<{cs}>(JsonOpts)!;\n"
            ));
        }
    }
    s.push_str("    }\n");
    s
}

// ---------------------------------------------------------------------------
// Naming + type helpers
// ---------------------------------------------------------------------------

/// `<PascalProvider><CapFirst(suffix)>` — the shared base for a method's C# name and its
/// request record. `characters.create` → `CharactersCreate`; `inventory.listMine` →
/// `InventoryListMine`.
fn op_base(method: &MethodDef) -> String {
    let suffix = method
        .wire_method
        .split_once('.')
        .map(|(_, s)| s)
        .unwrap_or(&method.wire_method);
    format!("{}{}", pascal_from_snake(&method.provider), cap_first(suffix))
}

/// The C# `Task`/`Task<T>` return type for a method's return `TypeRef`.
fn return_type(ret: &TypeRef) -> String {
    match ret {
        TypeRef::Unit => "Task".to_string(),
        other => format!("Task<{}>", cs_type(other)),
    }
}

/// Maps a value [`TypeRef`] to its C# type. `Unit` is not a value type — callers that can
/// see it (`return_type`) handle it before calling here.
fn cs_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "string".to_string(),
        TypeRef::I64 => "long".to_string(),
        TypeRef::Struct(name) => name.clone(),
        TypeRef::Vec(inner) => format!("{}[]", cs_type(inner)),
        TypeRef::Unit => "void".to_string(),
    }
}

/// `player_id` → `PlayerId`, `class` → `Class`, `topScores`/`create` unchanged-cased per
/// segment (already-camel single segments just get their first letter capitalized).
fn pascal_from_snake(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(cap_first)
        .collect()
}

/// `player_id` → `playerId`, `character_id` → `characterId`, `class` → `class`.
fn camel_from_snake(s: &str) -> String {
    lower_first(&pascal_from_snake(s))
}

fn cap_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// Prefixes a C# reserved keyword with `@` so it is a legal identifier (e.g. the
/// `class` arg → `@class`).
fn escape_ident(name: &str) -> String {
    if CS_KEYWORDS.contains(&name) {
        format!("@{name}")
    } else {
        name.to_string()
    }
}

/// The C# reserved keywords (identifiers that must be `@`-escaped when reused as a name).
const CS_KEYWORDS: &[&str] = &[
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
    "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
    "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
    "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
    "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
    "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
    "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
    "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
    "void", "volatile", "while",
];
