// Code generated by rpcgen; DO NOT EDIT.

package matchrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/match/matchapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodReport = "match.report"
)

// reportRequest is the wire request envelope for Report.
type reportRequest struct {
	Winner string `json:"winner"`
	Loser  string `json:"loser"`
}

// reportResponse is the wire response envelope for Report. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type reportResponse struct {
	Status opsapi.Status `json:"status"`
	Err    string        `json:"err,omitempty"`
}

// Client implements matchapi.Match over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ matchapi.Match = (*Client)(nil)

// Report implements the capability by calling match.report over the transport.
func (c *Client) Report(ctx context.Context, a0 string, a1 string) (err error) {
	req := reportRequest{Winner: a0, Loser: a1}
	var resp reportResponse
	if err = c.caller.Call(ctx, MethodReport, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl matchapi.Match) {
	reg.HandleIdentity(MethodReport, func(identity string, reqPayload []byte) ([]byte, error) {
		var req reportRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		err := impl.Report(opsapi.WithPlayerID(context.Background(), identity), req.Winner, req.Loser)
		resp := reportResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
		}
		return json.Marshal(resp)
	})
}
