// Code generated by rpcgen; DO NOT EDIT.

package matchrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/match/matchapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodReport = "match.report"
)

// reportRequest is the wire request envelope for Report.
type reportRequest struct {
	Winner string `json:"Winner"`
	Loser  string `json:"Loser"`
}

// reportResponse is the wire response envelope for Report. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type reportResponse struct {
	Status opsapi.Status `json:"status"`
	Err    string        `json:"err,omitempty"`
}

// Client implements matchapi.Match over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ matchapi.Match = (*Client)(nil)

// Report implements the capability by calling match.report over the transport.
func (c *Client) Report(ctx context.Context, a0 string, a1 string) (err error) {
	req := reportRequest{Winner: a0, Loser: a1}
	var resp reportResponse
	if err = c.caller.Call(ctx, MethodReport, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl matchapi.Match) {
	reg.HandleIdentity(MethodReport, func(identity string, reqPayload []byte) ([]byte, error) {
		var req reportRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		err := impl.Report(opsapi.WithPlayerID(context.Background(), identity), req.Winner, req.Loser)
		resp := reportResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
		}
		return json.Marshal(resp)
	})
}

// decodeReport builds the match.report wire request envelope from the HTTP body and path.
func decodeReport(body []byte, path map[string]string) (any, error) {
	var req reportRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeReport reduces the match.report wire response envelope to the external HTTP body + Status.
func encodeReport(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*reportResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	return nil, opsapi.StatusOK, nil
}

// Operations returns the gateway contributions for each HTTP-bound method of
// impl, keyed by wire method name. A module contributes each OpSet to the
// opsapi Slot/BindingSlot/LocalSlot; LocalBackend and RemoteBackend then share
// the SAME wire envelopes, so remote dispatch is correct for every op shape.
func Operations(impl matchapi.Match) map[string]opsapi.OpSet {
	return map[string]opsapi.OpSet{
		MethodReport: {
			Operation: opsapi.Operation{Method: MethodReport, Verb: "POST", Path: "/match/report", Auth: opsapi.AuthNone, Success: 202},
			Binding:   opsapi.OpBinding{Method: MethodReport, Decode: decodeReport, NewResp: func() any { return &reportResponse{} }, Encode: encodeReport},
			Local: opsapi.LocalOp{Method: MethodReport, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*reportRequest)
				err := impl.Report(ctx, rq.Winner, rq.Loser)
				out := resp.(*reportResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
				}
				return nil
			}},
		},
	}
}

// RouteBindings returns the impl-free route table for each HTTP-bound method:
// the Operation (route/auth/success) + its OpBinding (Decode/NewResp/Encode),
// with NO LocalOp. A remote-only front door (cmd/gateway-svc) builds its route
// table from this and dispatches each op over the edge — no provider impl needed.
func RouteBindings() []opsapi.RouteBinding {
	return []opsapi.RouteBinding{
		{
			Operation: opsapi.Operation{Method: MethodReport, Verb: "POST", Path: "/match/report", Auth: opsapi.AuthNone, Success: 202},
			Binding:   opsapi.OpBinding{Method: MethodReport, Decode: decodeReport, NewResp: func() any { return &reportResponse{} }, Encode: encodeReport},
		},
	}
}
