// Code generated by rpcgen; DO NOT EDIT.

package accountsrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/accounts/accountsapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodVerifySession = "accounts.verifySession"
)

// verifySessionRequest is the wire request envelope for VerifySession.
type verifySessionRequest struct {
	Token string `json:"token"`
}

// verifySessionResponse is the wire response envelope for VerifySession. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type verifySessionResponse struct {
	Status   opsapi.Status `json:"status"`
	Err      string        `json:"err,omitempty"`
	PlayerID string        `json:"playerID"`
	Ok       bool          `json:"ok"`
}

// Client implements accountsapi.Sessions over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ accountsapi.Sessions = (*Client)(nil)

// VerifySession implements the capability by calling accounts.verifySession over the transport.
func (c *Client) VerifySession(ctx context.Context, a0 string) (r0 string, r1 bool, err error) {
	req := verifySessionRequest{Token: a0}
	var resp verifySessionResponse
	if err = c.caller.Call(ctx, MethodVerifySession, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.PlayerID
	r1 = resp.Ok
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one handler per method. *edge.Server satisfies it.
type Registrar interface {
	Handle(method string, h edge.Handler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with context.Background() (matching
// the hand-written adapters — NO ctx propagation), and marshals the response
// envelope, folding a returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl accountsapi.Sessions) {
	reg.Handle(MethodVerifySession, func(reqPayload []byte) ([]byte, error) {
		var req verifySessionRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, r1, err := impl.VerifySession(context.Background(), req.Token)
		resp := verifySessionResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.PlayerID = r0
			resp.Ok = r1
		}
		return json.Marshal(resp)
	})
}
