package match

import (
	"gamebackend/lifecycle"
	"gamebackend/modules/match/matchapi"
	"gamebackend/modules/match/matchrpc"
	"gamebackend/opsapi"
)

// registerOps contributes the match module's single public operation (report).
// Route, HTTP↔wire binding and in-process invoker are all GENERATED by rpcgen from
// matchapi.Match + its HTTPBindings; the public body keys stay the Go-default
// capitalized Winner/Loser (BodyNames override), answered 202 with no body. match
// is monolith-only (no split service, no edge / RegisterServer), so only the
// LocalOp invoker is used. svc (*Module) satisfies matchapi.Match.
func registerOps(ctx *lifecycle.Context, svc *Module) {
	// Pass the module to the generated glue AS the pure capability interface.
	var impl matchapi.Match = svc
	for _, op := range matchrpc.Operations(impl) {
		ctx.Contribute(opsapi.Slot, op.Operation)
		ctx.Contribute(opsapi.BindingSlot, op.Binding)
		ctx.Contribute(opsapi.LocalSlot, op.Local)
	}
}
