package leaderboard

import (
	"gamebackend/lifecycle"
	"gamebackend/modules/leaderboard/leaderboardapi"
	"gamebackend/modules/leaderboard/leaderboardrpc"
	"gamebackend/opsapi"
)

// registerOps contributes the leaderboard's single public operation (topScores).
// Route, HTTP↔wire binding and in-process invoker are all GENERATED by rpcgen from
// leaderboardapi.Leaderboard + its HTTPBindings. leaderboard is monolith-only (no
// split service hosts it, no edge / RegisterServer), so only the LocalOp invoker is
// used; the generated Client/RegisterServer are unused here. svc (*Module)
// satisfies leaderboardapi.Leaderboard.
func registerOps(ctx *lifecycle.Context, svc *Module) {
	// Pass the module to the generated glue AS the pure capability interface.
	var impl leaderboardapi.Leaderboard = svc
	for _, op := range leaderboardrpc.Operations(impl) {
		ctx.Contribute(opsapi.Slot, op.Operation)
		ctx.Contribute(opsapi.BindingSlot, op.Binding)
		ctx.Contribute(opsapi.LocalSlot, op.Local)
	}
}
