// Code generated by rpcgen; DO NOT EDIT.

package inventoryrpc

import (
	"context"
	"encoding/json"
	"gamebackend/api/inventory/inventoryapi"
	"gamebackend/edge"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodGrant         = "inventory.grant"
	MethodListCharacter = "inventory.listCharacter"
	MethodListMine      = "inventory.listMine"
)

// grantRequest is the wire request envelope for Grant.
type grantRequest struct {
	ItemID string `json:"item_id"`
	Qty    int    `json:"qty"`
}

// grantResponse is the wire response envelope for Grant. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type grantResponse struct {
	Status   opsapi.Status          `json:"status"`
	Err      string                 `json:"err,omitempty"`
	Holdings []inventoryapi.Holding `json:"holdings"`
}

// listCharacterRequest is the wire request envelope for ListCharacter.
type listCharacterRequest struct {
	CharacterID string `json:"characterID"`
}

// listCharacterResponse is the wire response envelope for ListCharacter. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type listCharacterResponse struct {
	Status   opsapi.Status          `json:"status"`
	Err      string                 `json:"err,omitempty"`
	Holdings []inventoryapi.Holding `json:"holdings"`
}

// listMineRequest is the wire request envelope for ListMine.
type listMineRequest struct {
}

// listMineResponse is the wire response envelope for ListMine. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type listMineResponse struct {
	Status   opsapi.Status          `json:"status"`
	Err      string                 `json:"err,omitempty"`
	Holdings []inventoryapi.Holding `json:"holdings"`
}

// Client implements inventoryapi.Holdings over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ inventoryapi.Holdings = (*Client)(nil)

// Grant implements the capability by calling inventory.grant over the transport.
func (c *Client) Grant(ctx context.Context, a0 string, a1 int) (r0 []inventoryapi.Holding, err error) {
	req := grantRequest{ItemID: a0, Qty: a1}
	var resp grantResponse
	if err = c.caller.Call(ctx, MethodGrant, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Holdings
	return
}

// ListCharacter implements the capability by calling inventory.listCharacter over the transport.
func (c *Client) ListCharacter(ctx context.Context, a0 string) (r0 []inventoryapi.Holding, err error) {
	req := listCharacterRequest{CharacterID: a0}
	var resp listCharacterResponse
	if err = c.caller.Call(ctx, MethodListCharacter, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Holdings
	return
}

// ListMine implements the capability by calling inventory.listMine over the transport.
func (c *Client) ListMine(ctx context.Context) (r0 []inventoryapi.Holding, err error) {
	req := listMineRequest{}
	var resp listMineResponse
	if err = c.caller.Call(ctx, MethodListMine, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Holdings
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl inventoryapi.Holdings) {
	reg.HandleIdentity(MethodGrant, func(identity string, reqPayload []byte) ([]byte, error) {
		var req grantRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Grant(opsapi.WithPlayerID(context.Background(), identity), req.ItemID, req.Qty)
		resp := grantResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Holdings = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodListCharacter, func(identity string, reqPayload []byte) ([]byte, error) {
		var req listCharacterRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.ListCharacter(opsapi.WithPlayerID(context.Background(), identity), req.CharacterID)
		resp := listCharacterResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Holdings = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodListMine, func(identity string, reqPayload []byte) ([]byte, error) {
		var req listMineRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.ListMine(opsapi.WithPlayerID(context.Background(), identity))
		resp := listMineResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Holdings = r0
		}
		return json.Marshal(resp)
	})
}

// decodeGrant builds the inventory.grant wire request envelope from the HTTP body and path.
func decodeGrant(body []byte, path map[string]string) (any, error) {
	var req grantRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeGrant reduces the inventory.grant wire response envelope to the external HTTP body + Status.
func encodeGrant(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*grantResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Holdings)
	return body, opsapi.StatusOK, err
}

// decodeListCharacter builds the inventory.listCharacter wire request envelope from the HTTP body and path.
func decodeListCharacter(body []byte, path map[string]string) (any, error) {
	var req listCharacterRequest
	req.CharacterID = path["id"]
	return &req, nil
}

// encodeListCharacter reduces the inventory.listCharacter wire response envelope to the external HTTP body + Status.
func encodeListCharacter(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*listCharacterResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Holdings)
	return body, opsapi.StatusOK, err
}

// decodeListMine builds the inventory.listMine wire request envelope from the HTTP body and path.
func decodeListMine(body []byte, path map[string]string) (any, error) {
	var req listMineRequest
	return &req, nil
}

// encodeListMine reduces the inventory.listMine wire response envelope to the external HTTP body + Status.
func encodeListMine(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*listMineResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Holdings)
	return body, opsapi.StatusOK, err
}

// Operations returns the gateway contributions for each HTTP-bound method of
// impl, keyed by wire method name. A module contributes each OpSet to the
// opsapi Slot/BindingSlot/LocalSlot; LocalBackend and RemoteBackend then share
// the SAME wire envelopes, so remote dispatch is correct for every op shape.
func Operations(impl inventoryapi.Holdings) map[string]opsapi.OpSet {
	return map[string]opsapi.OpSet{
		MethodGrant: {
			Operation: opsapi.Operation{Method: MethodGrant, Verb: "POST", Path: "/inventory/me/grant", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodGrant, Decode: decodeGrant, NewResp: func() any { return &grantResponse{} }, Encode: encodeGrant},
			Local: opsapi.LocalOp{Method: MethodGrant, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*grantRequest)
				r0, err := impl.Grant(ctx, rq.ItemID, rq.Qty)
				out := resp.(*grantResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Holdings = r0
				}
				return nil
			}},
		},
		MethodListCharacter: {
			Operation: opsapi.Operation{Method: MethodListCharacter, Verb: "GET", Path: "/inventory/character/{id}", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodListCharacter, Decode: decodeListCharacter, NewResp: func() any { return &listCharacterResponse{} }, Encode: encodeListCharacter},
			Local: opsapi.LocalOp{Method: MethodListCharacter, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*listCharacterRequest)
				r0, err := impl.ListCharacter(ctx, rq.CharacterID)
				out := resp.(*listCharacterResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Holdings = r0
				}
				return nil
			}},
		},
		MethodListMine: {
			Operation: opsapi.Operation{Method: MethodListMine, Verb: "GET", Path: "/inventory/me", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodListMine, Decode: decodeListMine, NewResp: func() any { return &listMineResponse{} }, Encode: encodeListMine},
			Local: opsapi.LocalOp{Method: MethodListMine, Invoke: func(ctx context.Context, req, resp any) error {
				r0, err := impl.ListMine(ctx)
				out := resp.(*listMineResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Holdings = r0
				}
				return nil
			}},
		},
	}
}

// RouteBindings returns the impl-free route table for each HTTP-bound method:
// the Operation (route/auth/success) + its OpBinding (Decode/NewResp/Encode),
// with NO LocalOp. A remote-only front door (cmd/gateway-svc) builds its route
// table from this and dispatches each op over the edge — no provider impl needed.
func RouteBindings() []opsapi.RouteBinding {
	return []opsapi.RouteBinding{
		{
			Operation: opsapi.Operation{Method: MethodGrant, Verb: "POST", Path: "/inventory/me/grant", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodGrant, Decode: decodeGrant, NewResp: func() any { return &grantResponse{} }, Encode: encodeGrant},
		},
		{
			Operation: opsapi.Operation{Method: MethodListCharacter, Verb: "GET", Path: "/inventory/character/{id}", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodListCharacter, Decode: decodeListCharacter, NewResp: func() any { return &listCharacterResponse{} }, Encode: encodeListCharacter},
		},
		{
			Operation: opsapi.Operation{Method: MethodListMine, Verb: "GET", Path: "/inventory/me", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodListMine, Decode: decodeListMine, NewResp: func() any { return &listMineResponse{} }, Encode: encodeListMine},
		},
	}
}
