// Code generated by rpcgen; DO NOT EDIT.

package leaderboardrpc

import (
	"context"
	"encoding/json"
	"gamebackend/api/leaderboard/leaderboardapi"
	"gamebackend/edge"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodTopScores = "leaderboard.topScores"
)

// topScoresRequest is the wire request envelope for TopScores.
type topScoresRequest struct {
}

// topScoresResponse is the wire response envelope for TopScores. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type topScoresResponse struct {
	Status opsapi.Status          `json:"status"`
	Err    string                 `json:"err,omitempty"`
	Scores []leaderboardapi.Score `json:"scores"`
}

// Client implements leaderboardapi.Leaderboard over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ leaderboardapi.Leaderboard = (*Client)(nil)

// TopScores implements the capability by calling leaderboard.topScores over the transport.
func (c *Client) TopScores(ctx context.Context) (r0 []leaderboardapi.Score, err error) {
	req := topScoresRequest{}
	var resp topScoresResponse
	if err = c.caller.Call(ctx, MethodTopScores, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Scores
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl leaderboardapi.Leaderboard) {
	reg.HandleIdentity(MethodTopScores, func(identity string, reqPayload []byte) ([]byte, error) {
		var req topScoresRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.TopScores(opsapi.WithPlayerID(context.Background(), identity))
		resp := topScoresResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Scores = r0
		}
		return json.Marshal(resp)
	})
}

// decodeTopScores builds the leaderboard.topScores wire request envelope from the HTTP body and path.
func decodeTopScores(body []byte, path map[string]string) (any, error) {
	var req topScoresRequest
	return &req, nil
}

// encodeTopScores reduces the leaderboard.topScores wire response envelope to the external HTTP body + Status.
func encodeTopScores(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*topScoresResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Scores)
	return body, opsapi.StatusOK, err
}

// Operations returns the gateway contributions for each HTTP-bound method of
// impl, keyed by wire method name. A module contributes each OpSet to the
// opsapi Slot/BindingSlot/LocalSlot; LocalBackend and RemoteBackend then share
// the SAME wire envelopes, so remote dispatch is correct for every op shape.
func Operations(impl leaderboardapi.Leaderboard) map[string]opsapi.OpSet {
	return map[string]opsapi.OpSet{
		MethodTopScores: {
			Operation: opsapi.Operation{Method: MethodTopScores, Verb: "GET", Path: "/leaderboard", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodTopScores, Decode: decodeTopScores, NewResp: func() any { return &topScoresResponse{} }, Encode: encodeTopScores},
			Local: opsapi.LocalOp{Method: MethodTopScores, Invoke: func(ctx context.Context, req, resp any) error {
				r0, err := impl.TopScores(ctx)
				out := resp.(*topScoresResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Scores = r0
				}
				return nil
			}},
		},
	}
}

// RouteBindings returns the impl-free route table for each HTTP-bound method:
// the Operation (route/auth/success) + its OpBinding (Decode/NewResp/Encode),
// with NO LocalOp. A remote-only front door (cmd/gateway-svc) builds its route
// table from this and dispatches each op over the edge — no provider impl needed.
func RouteBindings() []opsapi.RouteBinding {
	return []opsapi.RouteBinding{
		{
			Operation: opsapi.Operation{Method: MethodTopScores, Verb: "GET", Path: "/leaderboard", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodTopScores, Decode: decodeTopScores, NewResp: func() any { return &topScoresResponse{} }, Encode: encodeTopScores},
		},
	}
}
