// Code generated by rpcgen; DO NOT EDIT.

package accountsauthrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/accounts/accountsapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodLogin     = "accounts.login"
	MethodLoginEpic = "accounts.loginEpic"
	MethodMe        = "accounts.me"
	MethodRegister  = "accounts.register"
)

// loginRequest is the wire request envelope for Login.
type loginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// loginResponse is the wire response envelope for Login. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type loginResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// loginEpicRequest is the wire request envelope for LoginEpic.
type loginEpicRequest struct {
	IdToken string `json:"idToken"`
}

// loginEpicResponse is the wire response envelope for LoginEpic. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type loginEpicResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// meRequest is the wire request envelope for Me.
type meRequest struct {
}

// meResponse is the wire response envelope for Me. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type meResponse struct {
	Status     opsapi.Status          `json:"status"`
	Err        string                 `json:"err,omitempty"`
	Player     accountsapi.Player     `json:"player"`
	Identities []accountsapi.Identity `json:"identities"`
}

// registerRequest is the wire request envelope for Register.
type registerRequest struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

// registerResponse is the wire response envelope for Register. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type registerResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// Client implements accountsapi.Auth over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ accountsapi.Auth = (*Client)(nil)

// Login implements the capability by calling accounts.login over the transport.
func (c *Client) Login(ctx context.Context, a0 string, a1 string) (r0 accountsapi.Session, err error) {
	req := loginRequest{Email: a0, Password: a1}
	var resp loginResponse
	if err = c.caller.Call(ctx, MethodLogin, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// LoginEpic implements the capability by calling accounts.loginEpic over the transport.
func (c *Client) LoginEpic(ctx context.Context, a0 string) (r0 accountsapi.Session, err error) {
	req := loginEpicRequest{IdToken: a0}
	var resp loginEpicResponse
	if err = c.caller.Call(ctx, MethodLoginEpic, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// Me implements the capability by calling accounts.me over the transport.
func (c *Client) Me(ctx context.Context) (r0 accountsapi.Player, r1 []accountsapi.Identity, err error) {
	req := meRequest{}
	var resp meResponse
	if err = c.caller.Call(ctx, MethodMe, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Player
	r1 = resp.Identities
	return
}

// Register implements the capability by calling accounts.register over the transport.
func (c *Client) Register(ctx context.Context, a0 string, a1 string, a2 string) (r0 accountsapi.Session, err error) {
	req := registerRequest{Email: a0, Password: a1, DisplayName: a2}
	var resp registerResponse
	if err = c.caller.Call(ctx, MethodRegister, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl accountsapi.Auth) {
	reg.HandleIdentity(MethodLogin, func(identity string, reqPayload []byte) ([]byte, error) {
		var req loginRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Login(opsapi.WithPlayerID(context.Background(), identity), req.Email, req.Password)
		resp := loginResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodLoginEpic, func(identity string, reqPayload []byte) ([]byte, error) {
		var req loginEpicRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.LoginEpic(opsapi.WithPlayerID(context.Background(), identity), req.IdToken)
		resp := loginEpicResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodMe, func(identity string, reqPayload []byte) ([]byte, error) {
		var req meRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, r1, err := impl.Me(opsapi.WithPlayerID(context.Background(), identity))
		resp := meResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Player = r0
			resp.Identities = r1
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodRegister, func(identity string, reqPayload []byte) ([]byte, error) {
		var req registerRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Register(opsapi.WithPlayerID(context.Background(), identity), req.Email, req.Password, req.DisplayName)
		resp := registerResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
}
