// Code generated by rpcgen; DO NOT EDIT.

package accountsauthrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/accounts/accountsapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodLogin     = "accounts.login"
	MethodLoginEpic = "accounts.loginEpic"
	MethodMe        = "accounts.me"
	MethodRegister  = "accounts.register"
)

// loginRequest is the wire request envelope for Login.
type loginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// loginResponse is the wire response envelope for Login. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type loginResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// loginEpicRequest is the wire request envelope for LoginEpic.
type loginEpicRequest struct {
	IdToken string `json:"id_token"`
}

// loginEpicResponse is the wire response envelope for LoginEpic. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type loginEpicResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// meRequest is the wire request envelope for Me.
type meRequest struct {
}

// meResponse is the wire response envelope for Me. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type meResponse struct {
	Status opsapi.Status      `json:"status"`
	Err    string             `json:"err,omitempty"`
	View   accountsapi.MeView `json:"view"`
}

// registerRequest is the wire request envelope for Register.
type registerRequest struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

// registerResponse is the wire response envelope for Register. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type registerResponse struct {
	Status  opsapi.Status       `json:"status"`
	Err     string              `json:"err,omitempty"`
	Session accountsapi.Session `json:"session"`
}

// Client implements accountsapi.Auth over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ accountsapi.Auth = (*Client)(nil)

// Login implements the capability by calling accounts.login over the transport.
func (c *Client) Login(ctx context.Context, a0 string, a1 string) (r0 accountsapi.Session, err error) {
	req := loginRequest{Email: a0, Password: a1}
	var resp loginResponse
	if err = c.caller.Call(ctx, MethodLogin, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// LoginEpic implements the capability by calling accounts.loginEpic over the transport.
func (c *Client) LoginEpic(ctx context.Context, a0 string) (r0 accountsapi.Session, err error) {
	req := loginEpicRequest{IdToken: a0}
	var resp loginEpicResponse
	if err = c.caller.Call(ctx, MethodLoginEpic, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// Me implements the capability by calling accounts.me over the transport.
func (c *Client) Me(ctx context.Context) (r0 accountsapi.MeView, err error) {
	req := meRequest{}
	var resp meResponse
	if err = c.caller.Call(ctx, MethodMe, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.View
	return
}

// Register implements the capability by calling accounts.register over the transport.
func (c *Client) Register(ctx context.Context, a0 string, a1 string, a2 string) (r0 accountsapi.Session, err error) {
	req := registerRequest{Email: a0, Password: a1, DisplayName: a2}
	var resp registerResponse
	if err = c.caller.Call(ctx, MethodRegister, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Session
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl accountsapi.Auth) {
	reg.HandleIdentity(MethodLogin, func(identity string, reqPayload []byte) ([]byte, error) {
		var req loginRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Login(opsapi.WithPlayerID(context.Background(), identity), req.Email, req.Password)
		resp := loginResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodLoginEpic, func(identity string, reqPayload []byte) ([]byte, error) {
		var req loginEpicRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.LoginEpic(opsapi.WithPlayerID(context.Background(), identity), req.IdToken)
		resp := loginEpicResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodMe, func(identity string, reqPayload []byte) ([]byte, error) {
		var req meRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Me(opsapi.WithPlayerID(context.Background(), identity))
		resp := meResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.View = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodRegister, func(identity string, reqPayload []byte) ([]byte, error) {
		var req registerRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Register(opsapi.WithPlayerID(context.Background(), identity), req.Email, req.Password, req.DisplayName)
		resp := registerResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Session = r0
		}
		return json.Marshal(resp)
	})
}

// decodeLogin builds the accounts.login wire request envelope from the HTTP body and path.
func decodeLogin(body []byte, path map[string]string) (any, error) {
	var req loginRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeLogin reduces the accounts.login wire response envelope to the external HTTP body + Status.
func encodeLogin(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*loginResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Session)
	return body, opsapi.StatusOK, err
}

// decodeLoginEpic builds the accounts.loginEpic wire request envelope from the HTTP body and path.
func decodeLoginEpic(body []byte, path map[string]string) (any, error) {
	var req loginEpicRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeLoginEpic reduces the accounts.loginEpic wire response envelope to the external HTTP body + Status.
func encodeLoginEpic(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*loginEpicResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Session)
	return body, opsapi.StatusOK, err
}

// decodeMe builds the accounts.me wire request envelope from the HTTP body and path.
func decodeMe(body []byte, path map[string]string) (any, error) {
	var req meRequest
	return &req, nil
}

// encodeMe reduces the accounts.me wire response envelope to the external HTTP body + Status.
func encodeMe(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*meResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.View)
	return body, opsapi.StatusOK, err
}

// decodeRegister builds the accounts.register wire request envelope from the HTTP body and path.
func decodeRegister(body []byte, path map[string]string) (any, error) {
	var req registerRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeRegister reduces the accounts.register wire response envelope to the external HTTP body + Status.
func encodeRegister(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*registerResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Session)
	return body, opsapi.StatusOK, err
}

// Operations returns the gateway contributions for each HTTP-bound method of
// impl, keyed by wire method name. A module contributes each OpSet to the
// opsapi Slot/BindingSlot/LocalSlot; LocalBackend and RemoteBackend then share
// the SAME wire envelopes, so remote dispatch is correct for every op shape.
func Operations(impl accountsapi.Auth) map[string]opsapi.OpSet {
	return map[string]opsapi.OpSet{
		MethodLogin: {
			Operation: opsapi.Operation{Method: MethodLogin, Verb: "POST", Path: "/accounts/login", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodLogin, Decode: decodeLogin, NewResp: func() any { return &loginResponse{} }, Encode: encodeLogin},
			Local: opsapi.LocalOp{Method: MethodLogin, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*loginRequest)
				r0, err := impl.Login(ctx, rq.Email, rq.Password)
				out := resp.(*loginResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Session = r0
				}
				return nil
			}},
		},
		MethodLoginEpic: {
			Operation: opsapi.Operation{Method: MethodLoginEpic, Verb: "POST", Path: "/accounts/login/epic", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodLoginEpic, Decode: decodeLoginEpic, NewResp: func() any { return &loginEpicResponse{} }, Encode: encodeLoginEpic},
			Local: opsapi.LocalOp{Method: MethodLoginEpic, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*loginEpicRequest)
				r0, err := impl.LoginEpic(ctx, rq.IdToken)
				out := resp.(*loginEpicResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Session = r0
				}
				return nil
			}},
		},
		MethodMe: {
			Operation: opsapi.Operation{Method: MethodMe, Verb: "GET", Path: "/accounts/me", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodMe, Decode: decodeMe, NewResp: func() any { return &meResponse{} }, Encode: encodeMe},
			Local: opsapi.LocalOp{Method: MethodMe, Invoke: func(ctx context.Context, req, resp any) error {
				r0, err := impl.Me(ctx)
				out := resp.(*meResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.View = r0
				}
				return nil
			}},
		},
		MethodRegister: {
			Operation: opsapi.Operation{Method: MethodRegister, Verb: "POST", Path: "/accounts/register", Auth: opsapi.AuthNone, Success: 201},
			Binding:   opsapi.OpBinding{Method: MethodRegister, Decode: decodeRegister, NewResp: func() any { return &registerResponse{} }, Encode: encodeRegister},
			Local: opsapi.LocalOp{Method: MethodRegister, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*registerRequest)
				r0, err := impl.Register(ctx, rq.Email, rq.Password, rq.DisplayName)
				out := resp.(*registerResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Session = r0
				}
				return nil
			}},
		},
	}
}

// RouteBindings returns the impl-free route table for each HTTP-bound method:
// the Operation (route/auth/success) + its OpBinding (Decode/NewResp/Encode),
// with NO LocalOp. A remote-only front door (cmd/gateway-svc) builds its route
// table from this and dispatches each op over the edge — no provider impl needed.
func RouteBindings() []opsapi.RouteBinding {
	return []opsapi.RouteBinding{
		{
			Operation: opsapi.Operation{Method: MethodLogin, Verb: "POST", Path: "/accounts/login", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodLogin, Decode: decodeLogin, NewResp: func() any { return &loginResponse{} }, Encode: encodeLogin},
		},
		{
			Operation: opsapi.Operation{Method: MethodLoginEpic, Verb: "POST", Path: "/accounts/login/epic", Auth: opsapi.AuthNone, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodLoginEpic, Decode: decodeLoginEpic, NewResp: func() any { return &loginEpicResponse{} }, Encode: encodeLoginEpic},
		},
		{
			Operation: opsapi.Operation{Method: MethodMe, Verb: "GET", Path: "/accounts/me", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodMe, Decode: decodeMe, NewResp: func() any { return &meResponse{} }, Encode: encodeMe},
		},
		{
			Operation: opsapi.Operation{Method: MethodRegister, Verb: "POST", Path: "/accounts/register", Auth: opsapi.AuthNone, Success: 201},
			Binding:   opsapi.OpBinding{Method: MethodRegister, Decode: decodeRegister, NewResp: func() any { return &registerResponse{} }, Encode: encodeRegister},
		},
	}
}
