// Code generated by rpcgen; DO NOT EDIT.

package charactersplayerrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/characters/charactersapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodCreate = "characters.create"
	MethodDelete = "characters.delete"
	MethodList   = "characters.list"
)

// createRequest is the wire request envelope for Create.
type createRequest struct {
	Name  string `json:"name"`
	Class string `json:"class"`
}

// createResponse is the wire response envelope for Create. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type createResponse struct {
	Status    opsapi.Status           `json:"status"`
	Err       string                  `json:"err,omitempty"`
	Character charactersapi.Character `json:"character"`
}

// deleteRequest is the wire request envelope for Delete.
type deleteRequest struct {
	CharacterID string `json:"characterID"`
}

// deleteResponse is the wire response envelope for Delete. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type deleteResponse struct {
	Status opsapi.Status `json:"status"`
	Err    string        `json:"err,omitempty"`
}

// listRequest is the wire request envelope for List.
type listRequest struct {
}

// listResponse is the wire response envelope for List. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type listResponse struct {
	Status     opsapi.Status             `json:"status"`
	Err        string                    `json:"err,omitempty"`
	Characters []charactersapi.Character `json:"characters"`
}

// Client implements charactersapi.Player over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ charactersapi.Player = (*Client)(nil)

// Create implements the capability by calling characters.create over the transport.
func (c *Client) Create(ctx context.Context, a0 string, a1 string) (r0 charactersapi.Character, err error) {
	req := createRequest{Name: a0, Class: a1}
	var resp createResponse
	if err = c.caller.Call(ctx, MethodCreate, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Character
	return
}

// Delete implements the capability by calling characters.delete over the transport.
func (c *Client) Delete(ctx context.Context, a0 string) (err error) {
	req := deleteRequest{CharacterID: a0}
	var resp deleteResponse
	if err = c.caller.Call(ctx, MethodDelete, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	return
}

// List implements the capability by calling characters.list over the transport.
func (c *Client) List(ctx context.Context) (r0 []charactersapi.Character, err error) {
	req := listRequest{}
	var resp listResponse
	if err = c.caller.Call(ctx, MethodList, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Characters
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl charactersapi.Player) {
	reg.HandleIdentity(MethodCreate, func(identity string, reqPayload []byte) ([]byte, error) {
		var req createRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.Create(opsapi.WithPlayerID(context.Background(), identity), req.Name, req.Class)
		resp := createResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Character = r0
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodDelete, func(identity string, reqPayload []byte) ([]byte, error) {
		var req deleteRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		err := impl.Delete(opsapi.WithPlayerID(context.Background(), identity), req.CharacterID)
		resp := deleteResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
		}
		return json.Marshal(resp)
	})
	reg.HandleIdentity(MethodList, func(identity string, reqPayload []byte) ([]byte, error) {
		var req listRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.List(opsapi.WithPlayerID(context.Background(), identity))
		resp := listResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Characters = r0
		}
		return json.Marshal(resp)
	})
}

// decodeCreate builds the characters.create wire request envelope from the HTTP body and path.
func decodeCreate(body []byte, path map[string]string) (any, error) {
	var req createRequest
	if len(body) > 0 {
		if err := json.Unmarshal(body, &req); err != nil {
			return nil, &opsapi.Error{Status: opsapi.StatusInvalid, Msg: "invalid json"}
		}
	}
	return &req, nil
}

// encodeCreate reduces the characters.create wire response envelope to the external HTTP body + Status.
func encodeCreate(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*createResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Character)
	return body, opsapi.StatusOK, err
}

// decodeDelete builds the characters.delete wire request envelope from the HTTP body and path.
func decodeDelete(body []byte, path map[string]string) (any, error) {
	var req deleteRequest
	req.CharacterID = path["id"]
	return &req, nil
}

// encodeDelete reduces the characters.delete wire response envelope to the external HTTP body + Status.
func encodeDelete(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*deleteResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	return nil, opsapi.StatusOK, nil
}

// decodeList builds the characters.list wire request envelope from the HTTP body and path.
func decodeList(body []byte, path map[string]string) (any, error) {
	var req listRequest
	return &req, nil
}

// encodeList reduces the characters.list wire response envelope to the external HTTP body + Status.
func encodeList(resp any) ([]byte, opsapi.Status, error) {
	r := resp.(*listResponse)
	if r.Status != opsapi.StatusOK {
		return nil, r.Status, &opsapi.Error{Status: r.Status, Msg: r.Err}
	}
	body, err := json.Marshal(r.Characters)
	return body, opsapi.StatusOK, err
}

// Operations returns the gateway contributions for each HTTP-bound method of
// impl, keyed by wire method name. A module contributes each OpSet to the
// opsapi Slot/BindingSlot/LocalSlot; LocalBackend and RemoteBackend then share
// the SAME wire envelopes, so remote dispatch is correct for every op shape.
func Operations(impl charactersapi.Player) map[string]opsapi.OpSet {
	return map[string]opsapi.OpSet{
		MethodCreate: {
			Operation: opsapi.Operation{Method: MethodCreate, Verb: "POST", Path: "/characters", Auth: opsapi.AuthPlayer, Success: 201},
			Binding:   opsapi.OpBinding{Method: MethodCreate, Decode: decodeCreate, NewResp: func() any { return &createResponse{} }, Encode: encodeCreate},
			Local: opsapi.LocalOp{Method: MethodCreate, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*createRequest)
				r0, err := impl.Create(ctx, rq.Name, rq.Class)
				out := resp.(*createResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Character = r0
				}
				return nil
			}},
		},
		MethodDelete: {
			Operation: opsapi.Operation{Method: MethodDelete, Verb: "DELETE", Path: "/characters/{id}", Auth: opsapi.AuthPlayer, Success: 204},
			Binding:   opsapi.OpBinding{Method: MethodDelete, Decode: decodeDelete, NewResp: func() any { return &deleteResponse{} }, Encode: encodeDelete},
			Local: opsapi.LocalOp{Method: MethodDelete, Invoke: func(ctx context.Context, req, resp any) error {
				rq := req.(*deleteRequest)
				err := impl.Delete(ctx, rq.CharacterID)
				out := resp.(*deleteResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
				}
				return nil
			}},
		},
		MethodList: {
			Operation: opsapi.Operation{Method: MethodList, Verb: "GET", Path: "/characters", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodList, Decode: decodeList, NewResp: func() any { return &listResponse{} }, Encode: encodeList},
			Local: opsapi.LocalOp{Method: MethodList, Invoke: func(ctx context.Context, req, resp any) error {
				r0, err := impl.List(ctx)
				out := resp.(*listResponse)
				if err != nil {
					out.Status = opsapi.StatusOf(err)
					out.Err = err.Error()
				} else {
					out.Status = opsapi.StatusOK
					out.Characters = r0
				}
				return nil
			}},
		},
	}
}

// RouteBindings returns the impl-free route table for each HTTP-bound method:
// the Operation (route/auth/success) + its OpBinding (Decode/NewResp/Encode),
// with NO LocalOp. A remote-only front door (cmd/gateway-svc) builds its route
// table from this and dispatches each op over the edge — no provider impl needed.
func RouteBindings() []opsapi.RouteBinding {
	return []opsapi.RouteBinding{
		{
			Operation: opsapi.Operation{Method: MethodCreate, Verb: "POST", Path: "/characters", Auth: opsapi.AuthPlayer, Success: 201},
			Binding:   opsapi.OpBinding{Method: MethodCreate, Decode: decodeCreate, NewResp: func() any { return &createResponse{} }, Encode: encodeCreate},
		},
		{
			Operation: opsapi.Operation{Method: MethodDelete, Verb: "DELETE", Path: "/characters/{id}", Auth: opsapi.AuthPlayer, Success: 204},
			Binding:   opsapi.OpBinding{Method: MethodDelete, Decode: decodeDelete, NewResp: func() any { return &deleteResponse{} }, Encode: encodeDelete},
		},
		{
			Operation: opsapi.Operation{Method: MethodList, Verb: "GET", Path: "/characters", Auth: opsapi.AuthPlayer, Success: 200},
			Binding:   opsapi.OpBinding{Method: MethodList, Decode: decodeList, NewResp: func() any { return &listResponse{} }, Encode: encodeList},
		},
	}
}
