// Code generated by rpcgen; DO NOT EDIT.

package leaderboardrpc

import (
	"context"
	"encoding/json"
	"gamebackend/edge"
	"gamebackend/modules/leaderboard/leaderboardapi"
	"gamebackend/opsapi"
)

// Method names are the wire identifiers the client sends and the server
// registers under.
const (
	MethodTopScores = "leaderboard.topScores"
)

// topScoresRequest is the wire request envelope for TopScores.
type topScoresRequest struct {
}

// topScoresResponse is the wire response envelope for TopScores. Status/Err carry the
// operation outcome (opsapi taxonomy); the fields carry the return values.
type topScoresResponse struct {
	Status opsapi.Status          `json:"status"`
	Err    string                 `json:"err,omitempty"`
	Scores []leaderboardapi.Score `json:"scores"`
}

// Client implements leaderboardapi.Leaderboard over an opsapi.Caller, marshaling each call
// into its wire envelope. It is the split-topology client; in the monolith the
// real service is called directly.
type Client struct {
	caller opsapi.Caller
}

// NewClient returns a Client that calls through caller.
func NewClient(caller opsapi.Caller) *Client { return &Client{caller: caller} }

var _ leaderboardapi.Leaderboard = (*Client)(nil)

// TopScores implements the capability by calling leaderboard.topScores over the transport.
func (c *Client) TopScores(ctx context.Context) (r0 []leaderboardapi.Score, err error) {
	req := topScoresRequest{}
	var resp topScoresResponse
	if err = c.caller.Call(ctx, MethodTopScores, &req, &resp); err != nil {
		return
	}
	if resp.Status != opsapi.StatusOK {
		err = &opsapi.Error{Status: resp.Status, Msg: resp.Err}
		return
	}
	r0 = resp.Scores
	return
}

// Registrar is the subset of *edge.Server the generated adapters install onto:
// one identity-aware handler per method. *edge.Server satisfies it.
type Registrar interface {
	HandleIdentity(method string, h edge.IdentityHandler)
}

// RegisterServer installs one edge adapter per method of impl onto reg. Each
// adapter unmarshals the request, calls impl with a context carrying the request
// envelope's Identity as the verified caller player_id (opsapi.WithPlayerID) — the
// trust boundary: identity is read ONLY from the (mutually authenticated) envelope,
// never a client-supplied field — and marshals the response envelope, folding a
// returned error into Status/Err via opsapi.StatusOf.
func RegisterServer(reg Registrar, impl leaderboardapi.Leaderboard) {
	reg.HandleIdentity(MethodTopScores, func(identity string, reqPayload []byte) ([]byte, error) {
		var req topScoresRequest
		if err := json.Unmarshal(reqPayload, &req); err != nil {
			return nil, err
		}
		r0, err := impl.TopScores(opsapi.WithPlayerID(context.Background(), identity))
		resp := topScoresResponse{}
		if err != nil {
			resp.Status = opsapi.StatusOf(err)
			resp.Err = err.Error()
		} else {
			resp.Status = opsapi.StatusOK
			resp.Scores = r0
		}
		return json.Marshal(resp)
	})
}
