package inventory

import (
	"gamebackend/lifecycle"
	"gamebackend/modules/inventory/inventoryapi"
	"gamebackend/modules/inventory/inventoryrpc"
	"gamebackend/opsapi"
)

// registerPlayerOps contributes the player operations. Route, HTTP↔wire binding
// and in-process invoker are all GENERATED by rpcgen from inventoryapi.Holdings +
// its HTTPBindings, so the gateway's LocalBackend and RemoteBackend consume the
// SAME wire envelopes. listMine/listCharacter are always exposed; grant is
// contributed only when devGrant is set (INVENTORY_DEV_GRANT), mirroring the old
// conditional route registration. svc (a *service) satisfies inventoryapi.Holdings.
func registerPlayerOps(ctx *lifecycle.Context, svc *service, devGrant bool) {
	// Pass the service to the generated glue AS the pure capability interface.
	var impl inventoryapi.Holdings = svc
	ops := inventoryrpc.Operations(impl)
	contributeOp(ctx, ops[inventoryrpc.MethodListMine])
	contributeOp(ctx, ops[inventoryrpc.MethodListCharacter])
	if devGrant {
		contributeOp(ctx, ops[inventoryrpc.MethodGrant])
	}
}

// contributeOp contributes one generated operation to the three gateway slots.
func contributeOp(ctx *lifecycle.Context, op opsapi.OpSet) {
	ctx.Contribute(opsapi.Slot, op.Operation)
	ctx.Contribute(opsapi.BindingSlot, op.Binding)
	ctx.Contribute(opsapi.LocalSlot, op.Local)
}
