// @generated by tools/opscatalog-gen -- DO NOT EDIT BY HAND.
// Regenerate: cargo run -p opscatalog-gen (freshness-gated by verifyctl codegen-freshness).
// Source: every #[http]-bound operation's route_bindings() across api/*/api, sorted by method.
pub const OPERATIONS: &[OpInfo] = &[
    OpInfo { method: "accounts.createGuest", verb: "POST", path: "/accounts/guest", auth: "none" },
    OpInfo { method: "accounts.login", verb: "POST", path: "/accounts/login", auth: "none" },
    OpInfo { method: "accounts.loginFederated", verb: "POST", path: "/accounts/login/federated", auth: "none" },
    OpInfo { method: "accounts.me", verb: "GET", path: "/accounts/me", auth: "player" },
    OpInfo { method: "accounts.register", verb: "POST", path: "/accounts/register", auth: "none" },
    OpInfo { method: "characters.create", verb: "POST", path: "/characters", auth: "player" },
    OpInfo { method: "characters.delete", verb: "DELETE", path: "/characters/{id}", auth: "player" },
    OpInfo { method: "characters.list", verb: "GET", path: "/characters", auth: "player" },
    OpInfo { method: "inventory.grant", verb: "POST", path: "/inventory/me/grant", auth: "player" },
    OpInfo { method: "inventory.listCharacter", verb: "GET", path: "/inventory/character/{id}", auth: "player" },
    OpInfo { method: "inventory.listMine", verb: "GET", path: "/inventory/me", auth: "player" },
    OpInfo { method: "leaderboard.topScores", verb: "GET", path: "/leaderboard", auth: "none" },
    OpInfo { method: "match.report", verb: "POST", path: "/match/report", auth: "none" },
    OpInfo { method: "wallet.listCurrencies", verb: "GET", path: "/wallet/currencies", auth: "player" },
    OpInfo { method: "wallet.myBalances", verb: "GET", path: "/wallet/me", auth: "player" },
];
